Document multi-part ids
HarperDB/documentation pull request #119
Opened 2024-09-24 13:59 UTC by kriszyp

2024-09-24 14:13 UTC, kriszyp commented
@kylebernhardy just wanted to verify that this is what you were looking for.

2024-09-24 14:49 UTC, jcohen-hdb reviewed
I caught two little formatting things, but I pushed those fixes to the branch. Conceptually this makes sense to me. Thanks!

2024-09-24 14:49 UTC, jcohen-hdb commented on docs/developers/real-time.md
> +When using nested topics, these are translated to multipart ids. The primary key/id for `my-resource/nested/id` would be `["nested","id]` in the database. This allows for a simple and effective way t
`["nested","id]` looks like it's missing a quote at the end.

2024-09-24 14:49 UTC, jcohen-hdb commented on docs/developers/rest.md
> +{ "id": ["electronics", "123"], name": "An electronic product" }
`name":` is missing an opening quote

2024-09-24 16:34 UTC, Ethan-Arrowood requested changes
looks good!

2024-09-24 16:34 UTC, Ethan-Arrowood commented on docs/developers/rest.md
> +let url = `/my-resource/?${new URLSearchParams(conditions)}`
Generally, I like a different pattern for URL creation...

```js
const url = new URL(`http://${process.env.HOST}/my-resource`);
url.searchParams.set(category, "software");
url.searchParams.set(price, 100);
// now `url` is fully useable either directly in `fetch` like...
fetch(url);
// or you can print it out easily with
console.log(url.toString())
```

2024-09-24 16:34 UTC, Ethan-Arrowood commented on docs/technical-details/reference/resource.md
> +The `search method` will return an `AsyncIterable` that can be iterated through to access the results of the query. In order to access the elements of the query results, you must use a `for await` lo
```suggestion
The `search method` will return an [`AsyncIterable`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncIterator) that can be iterated through to access the results of the query. In order to access the elements of the query results, you must use a `for await` loop (it does _not_ return an array, you can not access the results by index).
```

Lets link to the best docs on Async Iterables

2024-09-24 16:34 UTC, Ethan-Arrowood commented on docs/technical-details/reference/resource.md
> +for (let record of Table.search({ conditions: [...]})) {
```suggestion
for await (let record of Table.search({ conditions: [...]})) {
```
missing `await`

2024-09-27 02:38 UTC, Ethan-Arrowood approved these changes

2025-07-30 23:31 UTC, closed without merging